#!/bin/bash

# Run test.py and capture its output in the variable mynum
mynum=$(python3 test.py)

if [! "$mynum" -eq 200 ]; then
# or you can do is if [ "$mynum" -ne 200 ]; then (-ne )
    echo "The condition is true."
elif [ "$mynum" -eq 500 ];then 
    echo "The condition is 500"
else
    echo "The condition  is neither 200 ner 500"
fi
